### PR TITLE
remove duplicate tags in event creation

### PR DESCRIPTION
**Pull request by mrturkmen06**
Signed-off-by: Ahmet Turkmen <f.ahmet.turkmen@icloud.com>

- Duplicated tags from incoming create event request deleted.

### CODE REVIEW

**Comment by mrturkmen06** [comment]
There is no relationship between #421 and the changes in this pull request @gianmarcomennecozzi

**Comment by mrturkmen06** [comment]
Why did you think so ?

**Comment by gianmarcomennecozzi** [comment]
yeah thats true but to solve that problem i think its good to have that for loop anyway

**Comment by mrturkmen06** [comment]
> yeah thats true but to solve that problem i think its good to have that for loop anyway

I could not understand the reason of it,  could you a little bit explain @gianmarcomennecozzi ?

**Comment by mrturkmen06** [comment]
@gianmarcomennecozzi, I did not understand your point, but anyway, if you would like to explain, I am always available. 

I am merging changes.

**Pull request merged**
